project_id = "qxiadvdbmrcetghtqywa"

[functions.receive-email]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false
